
services:
  api:
    build: .
    ports:
      - "4000:4000"
    env_file: .env.example
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongo-data:
